name: Build de projeto

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy-web:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout para branch main
      uses: actions/checkout@v2

    - name: Configura NodeJs
      uses: actions/setup-node@v2
      with:
          node-version: "16.x"
    - name: Configurar Yarn 
      run: npm install -g yarn

    - name: Instalar dependencias
      run: yarn install

    - name: Buildar projeto
      run: yarn build
